### ISSUE TITLE
Problem with "Osoby > Rejestry zawodowe > Medycyna > Centralny Rejestr Lekarzy"

### ISSUE THREAD

**Issue by grabowskiadrian** [P3run/otwartezrodla#4]
Site configured for "Centralny Rejestr Lekarzy" is "https://rejestr.nil.org.pl/xml/nil/rejlek/hurtd". This site return error 404. 

I think it should be: https://rejestr.nil.org.pl

```
{
  "name": "Centralny Rejestr Lekarzy",
  "type": "url",
  "url": "https://rejestr.nil.org.pl/xml/nil/rejlek/hurtd"
}
```

**Comment by P3run** [comment]
Done.
